const citiesData = {
    Lagos: {
      name: 'Lagos',
      image: '../src/assets/ciudades/lagos.jpg',
      details: 'Lagos es la ciudad más grande de Nigeria y uno de los centros financieros de África. Es conocida por sus playas y su vida nocturna vibrante.',
      pointsOfInterest: ['Victoria Island', 'Lekki Conservation Centre', 'National Museum Lagos'],
    },
    Abuja: {
      name: 'Abuja',
      image: '../src/assets/ciudades/abuja.jpg',
      details: 'Abuja es la capital de Nigeria, famosa por su planificación urbana moderna y su arquitectura única.',
      pointsOfInterest: ['Aso Rock', 'National Mosque', 'National Assembly'],
    },
    Ibadan: {
      name: 'Ibadan',
      image: '../src/assets/ciudades/ibadan.jpg',
      details: 'Ibadan es una ciudad histórica en Nigeria conocida por su cultura rica y su importancia como centro educativo.',
      pointsOfInterest: ['University of Ibadan', 'Cocoa House', 'Ibadan National Museum'],
    },
    'El Cairo': {
      name: 'El Cairo',
      image: '../src/assets/ciudades/el-cairo.jpg',
      details: 'El Cairo es la capital de Egipto y es conocida por sus monumentos históricos, incluyendo las pirámides de Giza y el Museo Egipcio.',
      pointsOfInterest: ['Pirámides de Giza', 'Museo Egipcio', 'Bazar Khan el-Khalili'],
    },
    Alejandría: {
      name: 'Alejandría',
      image: '../src/assets/ciudades/alejandria.jpg',
      details: 'Alejandría es una ciudad portuaria en Egipto, famosa por su faro antiguo y su rica historia cultural.',
      pointsOfInterest: ['Biblioteca de Alejandría', 'Fortaleza de Qaitbay', 'Jardín de Montaza'],
    },
    Giza: {
      name: 'Giza',
      image: '../src/assets/ciudades/giza.jpg',
      details: 'Giza es conocida por albergar las famosas Pirámides de Giza y la Esfinge, monumentos emblemáticos de la civilización egipcia.',
      pointsOfInterest: ['Pirámides de Giza', 'La Esfinge', 'Museo del Barco Solar'],
    },
    'Ciudad del Cabo': {
      name: 'Ciudad del Cabo',
      image: '../src/assets/ciudades/ciudad-del-cabo.jpg',
      details: 'Ciudad del Cabo es conocida por su paisaje espectacular, incluyendo la montaña de la Mesa y sus playas vírgenes.',
      pointsOfInterest: ['Monte de la Mesa', 'Jardín Botánico de Kirstenbosch', 'Victoria & Alfred Waterfront'],
    },
    Johannesburgo: {
      name: 'Johannesburgo',
      image: '../src/assets/ciudades/johannesburgo.jpg',
      details: 'Johannesburgo es una ciudad dinámica en Sudáfrica, conocida por su historia minera y su desarrollo económico.',
      pointsOfInterest: ['Apartheid Museum', 'Gold Reef City', 'Maboneng Precinct'],
    },
    Durban: {
      name: 'Durban',
      image: '../src/assets/ciudades/durban.jpg',
      details: 'Durban es una ciudad costera en Sudáfrica, famosa por sus playas y su rica herencia cultural.',
      pointsOfInterest: ['Golden Mile', 'Durban Botanic Gardens', 'uShaka Marine World'],
    },
    Marrakech: {
      name: 'Marrakech',
      image: '../src/assets/ciudades/marrakech.jpg',
      details: 'Marrakech es una ciudad histórica en Marruecos, conocida por su medina vibrante y sus mercados tradicionales.',
      pointsOfInterest: ['Jardin Majorelle', 'Palacio Bahía', 'Medina de Marrakech'],
    },
    Casablanca: {
      name: 'Casablanca',
      image: '../src/assets/ciudades/casablanca.jpg',
      details: 'Casablanca es una ciudad costera en Marruecos, famosa por su arquitectura modernista y su puerto.',
      pointsOfInterest: ['Hassan II Mosque', 'Royal Palace of Casablanca', 'Old Medina'],
    },
    Fez: {
      name: 'Fez',
      image: '../src/assets/ciudades/fez.jpg',
      details: 'Fez es una ciudad en Marruecos, conocida por su medina antigua y sus históricas escuelas coránicas.',
      pointsOfInterest: ['Medina de Fez', 'Universidad Al Quaraouiyine', 'Tanneries de Fez'],
    },
    'Nueva York': {
      name: 'Nueva York',
      image: '../src/assets/ciudades/nueva-york.jpg',
      details: 'Nueva York es una de las ciudades más icónicas del mundo, conocida por sus rascacielos, Broadway y su vibrante vida urbana.',
      pointsOfInterest: ['Estatua de la Libertad', 'Central Park', 'Times Square'],
    },
    'Los Ángeles': {
      name: 'Los Ángeles',
      image: '../src/assets/ciudades/los-angeles.jpg',
      details: 'Los Ángeles es famosa por su industria del entretenimiento, sus playas y su cultura diversa.',
      pointsOfInterest: ['Hollywood Walk of Fame', 'Santa Monica Pier', 'Griffith Observatory'],
    },
    'Las Vegas': {
      name: 'Las Vegas',
      image: '../src/assets/ciudades/las-vegas.jpg',
      details: 'Las Vegas es conocida por sus casinos, espectáculos y su vibrante vida nocturna.',
      pointsOfInterest: ['Las Vegas Strip', 'Bellagio Fountains', 'Fremont Street Experience'],
    },
    Toronto: {
      name: 'Toronto',
      image: '../src/assets/ciudades/toronto.jpg',
      details: 'Toronto es la ciudad más grande de Canadá, conocida por su diversidad cultural y su impresionante horizonte.',
      pointsOfInterest: ['CN Tower', 'Royal Ontario Museum', 'Toronto Islands'],
    },
    Vancouver: {
      name: 'Vancouver',
      image: '../src/assets/ciudades/vancouver.jpg',
      details: 'Vancouver es conocida por su impresionante paisaje natural, incluyendo montañas y costas, y su vida urbana vibrante.',
      pointsOfInterest: ['Stanley Park', 'Granville Island', 'Capilano Suspension Bridge'],
    },
    Montreal: {
      name: 'Montreal',
      image: '../src/assets/ciudades/montreal.jpg',
      details: 'Montreal es una ciudad bilingüe en Canadá, famosa por su rica historia, su arquitectura y su escena cultural.',
      pointsOfInterest: ['Old Montreal', 'Mont Royal', 'Biodome de Montreal'],
    },
    'Ciudad de México': {
      name: 'Ciudad de México',
      image: '../src/assets/ciudades/ciudad-de-mexico.jpg',
      details: 'Ciudad de México es la capital de México, conocida por su rica historia, su arquitectura colonial y su vibrante vida cultural.',
      pointsOfInterest: ['Zócalo', 'Museo Frida Kahlo', 'Templo Mayor'],
    },
    Cancún: {
      name: 'Cancún',
      image: '../src/assets/ciudades/cancun.jpg',
      details: 'Cancún es conocida por sus playas de arena blanca, su vida nocturna y sus resorts de lujo.',
      pointsOfInterest: ['Playa Delfines', 'Isla Mujeres', 'Chichén Itzá'],
    },
    Guadalajara: {
      name: 'Guadalajara',
      image: '../src/assets/ciudades/guadalajara.jpg',
      details: 'Guadalajara es famosa por su rica herencia cultural, su música mariachi y su arquitectura histórica.',
      pointsOfInterest: ['Teatro Degollado', 'Hospicio Cabañas', 'Plaza de Armas'],
    },
    'La Habana': {
      name: 'La Habana',
      image: '../src/assets/ciudades/la-habana.jpg',
      details: 'La Habana es la capital de Cuba, conocida por su arquitectura colonial y su vibrante escena cultural.',
      pointsOfInterest: ['Malecón', 'Habana Vieja', 'Museo Nacional de Bellas Artes'],
    },
    Varadero: {
      name: 'Varadero',
      image: '../src/assets/ciudades/varadero.jpg',
      details: 'Varadero es conocida por sus playas paradisíacas y sus resorts todo incluido.',
      pointsOfInterest: ['Playa Varadero', 'Cueva de Ambrosio', 'Parque Josone'],
    },
    'Santiago de Cuba': {
      name: 'Santiago de Cuba',
      image: '../src/assets/ciudades/santiago-de-cuba.jpg',
      details: 'Santiago de Cuba es conocida por su rica herencia afro-cubana y su vibrante música.',
      pointsOfInterest: ['Castillo del Morro', 'Plaza de la Revolución', 'Céspedes Park'],
    },
    'Río de Janeiro': {
      name: 'Río de Janeiro',
      image: '../src/assets/ciudades/rio-de-janeiro.jpg',
      details: 'Río de Janeiro es famosa por su carnaval, sus playas y su icónico Cristo Redentor.',
      pointsOfInterest: ['Cristo Redentor', 'Pan de Azúcar', 'Copacabana Beach'],
    },
    'São Paulo': {
      name: 'São Paulo',
      image: '../src/assets/ciudades/sao-paulo.jpg',
      details: 'São Paulo es la ciudad más grande de Brasil, conocida por su vibrante vida cultural y su escena gastronómica.',
      pointsOfInterest: ['Avenida Paulista', 'Parque Ibirapuera', 'Museo de Arte de São Paulo'],
    },
    Salvador: {
      name: 'Salvador',
      image: '../src/assets/ciudades/salvador.jpg',
      details: 'Salvador es conocida por su rica herencia afro-brasileña y sus festivales coloridos.',
      pointsOfInterest: ['Pelourinho', 'Iglesia de San Francisco', 'Elevador Lacerda'],
    },
    'Buenos Aires': {
      name: 'Buenos Aires',
      image: '../src/assets/ciudades/buenos-aires.jpg',
      details: 'Buenos Aires es la capital de Argentina, conocida por su arquitectura europea y su vibrante vida cultural.',
      pointsOfInterest: ['Casa Rosada', 'Teatro Colón', 'Barrio La Boca'],
    },
    Córdoba: {
      name: 'Córdoba',
      image: '../src/assets/ciudades/cordoba.jpg',
      details: 'Córdoba es conocida por su rica historia colonial y su universidad histórica.',
      pointsOfInterest: ['Iglesia de los Jesuitas', 'Manzana Jesuítica', 'Parque Sarmiento'],
    },
    Mendoza: {
      name: 'Mendoza',
      image: '../src/assets/ciudades/mendoza.jpg',
      details: 'Mendoza es famosa por sus bodegas de vino y su impresionante paisaje montañoso.',
      pointsOfInterest: ['Parque General San Martín', 'Bodegas de Vino', 'Aconcagua'],
    },
    Santiago: {
      name: 'Santiago',
      image: '../src/assets/ciudades/santiago.jpg',
      details: 'Santiago es la capital de Chile, conocida por su mezcla de modernidad y tradición.',
      pointsOfInterest: ['Cerro San Cristóbal', 'Plaza de Armas', 'Museo de la Memoria'],
    },
    Valparaíso: {
      name: 'Valparaíso',
      image: '../src/assets/ciudades/valparaiso.jpg',
      details: 'Valparaíso es conocida por su puerto histórico y su vibrante escena artística.',
      pointsOfInterest: ['Cerro Alegre', 'Museo de Bellas Artes', 'Ascensores de Valparaíso'],
    },
    'San Pedro de Atacama': {
      name: 'San Pedro de Atacama',
      image: '../src/assets/ciudades/san-pedro-de-atacama.jpg',
      details: 'San Pedro de Atacama es conocida por su paisaje desértico y sus impresionantes formaciones geológicas.',
      pointsOfInterest: ['Valle de la Luna', 'Salar de Atacama', 'Geysers del Tatio'],
    },
    Lima: {
      
      name: 'Lima',
      image: '../src/assets/ciudades/lima.jpg',
      details: 'Lima es la capital de Perú, conocida por su rica herencia cultural y su escena culinaria.',
      pointsOfInterest: ['Plaza Mayor', 'Museo Larco', 'Parque Kennedy'],
    },
    Cusco: {
      name: 'Cusco',
      image: '../src/assets/ciudades/cusco.jpg',
      details: 'Cusco es conocida por su importancia histórica como la antigua capital del Imperio Inca.',
      pointsOfInterest: ['Machu Picchu', 'Sacsayhuamán', 'Plaza de Armas'],
    },
    Arequipa: {
      name: 'Arequipa',
      image: '../src/assets/ciudades/arequipa.jpg',
      details: 'Arequipa es conocida por su arquitectura colonial y su impresionante entorno montañoso.',
      pointsOfInterest: ['Monasterio de Santa Catalina', 'Plaza de Armas', 'Cañón del Colca'],
    },
    'San José': {
      name: 'San José',
      image: '../src/assets/ciudades/san-jose.jpg',
      details: 'San José es la capital de Costa Rica, conocida por su vibrante vida cultural y su arquitectura colonial.',
      pointsOfInterest: ['Museo del Oro', 'Teatro Nacional', 'Parque Metropolitano La Sabana'],
    },
    'Puerto Limón': {
      name: 'Puerto Limón',
      image: '../src/assets/ciudades/puerto-limon.jpg',
      details: 'Puerto Limón es un puerto en la costa caribeña de Costa Rica, famoso por su ambiente relajado y su rica biodiversidad.',
      pointsOfInterest: ['Parque Vargas', 'Jardín Botánico de Talamanca', 'Cahuita National Park'],
    },
    Monteverde: {
      name: 'Monteverde',
      image: '../src/assets/ciudades/monteverde.jpg',
      details: 'Monteverde es conocida por su bosque nuboso y sus emocionantes actividades ecoturísticas.',
      pointsOfInterest: ['Reserva Biológica Bosque Nuboso', 'Puentes Colgantes', 'Santuario de los Murciélagos'],
    },
    'Ciudad de Panamá': {
      name: 'Ciudad de Panamá',
      image: '../src/assets/ciudades/ciudad-de-panama.jpg',
      details: 'Ciudad de Panamá es la capital de Panamá, conocida por su vibrante vida nocturna y su impresionante canal.',
      pointsOfInterest: ['Canal de Panamá', 'Casco Viejo', 'Biomuseo'],
    },
    'Bocas del Toro': {
      name: 'Bocas del Toro',
      image: '../src/assets/ciudades/bocas-del-toro.jpg',
      details: 'Bocas del Toro es un archipiélago conocido por sus playas paradisíacas y su ambiente relajado.',
      pointsOfInterest: ['Playa Estrella', 'Isla Bastimentos', 'Parque Nacional Marino Isla Bastimentos'],
    },
    Boquete: {
      name: 'Boquete',
      image: '../src/assets/ciudades/boquete.jpg',
      details: 'Boquete es conocida por su clima templado, sus plantaciones de café y sus impresionantes paisajes montañosos.',
      pointsOfInterest: ['Volcán Barú', 'Sendero Los Quetzales', 'Jardín de Orquídeas'],
    },
    'Ciudad de Guatemala': {
      name: 'Ciudad de Guatemala',
      image: '../src/assets/ciudades/ciudad-de-guatemala.jpg',
      details: 'Ciudad de Guatemala es la capital de Guatemala, conocida por su rica historia y su arquitectura colonial.',
      pointsOfInterest: ['Plaza Mayor', 'Palacio Nacional de la Cultura', 'Museo Nacional de Arqueología'],
    },
    'Antigua Guatemala': {
      name: 'Antigua Guatemala',
      image: '../src/assets/ciudades/antigua-guatemala.jpg',
      details: 'Antigua Guatemala es famosa por su bien conservada arquitectura colonial y su ambiente histórico.',
      pointsOfInterest: ['Arco de Santa Catalina', 'Catedral de Antigua', 'Museo de Arte Colonial'],
    },
    Tikal: {
      name: 'Tikal',
      image: '../src/assets/ciudades/tikal.jpg',
      details: 'Tikal es una antigua ciudad maya en Guatemala, conocida por sus impresionantes ruinas arqueológicas.',
      pointsOfInterest: ['Templo I', 'Templo II', 'Gran Plaza'],
    },
    'Tegucigalpa': {
      name: 'Tegucigalpa',
      image: '../src/assets/ciudades/tegucigalpa.jpg',
      details: 'Tegucigalpa es la capital de Honduras, conocida por su entorno montañoso y su vibrante vida urbana.',
      pointsOfInterest: ['Parque Central', 'Museo para la Identidad Nacional', 'Catedral Metropolitana'],
    },
    Roatán: {
      name: 'Roatán',
      image: '../src/assets/ciudades/roatán.jpg',
      details: 'Roatán es una isla en el Caribe de Honduras, famosa por sus playas de arena blanca y sus excelentes oportunidades para el buceo.',
      pointsOfInterest: ['West Bay Beach', 'Parque Nacional Marino de Roatán', 'Isla de los Delfines'],
    },
    'San Pedro Sula': {
      name: 'San Pedro Sula',
      image: '../src/assets/ciudades/san-pedro-sula.jpg',
      details: 'San Pedro Sula es una ciudad importante en Honduras, conocida por su comercio y su industria.',
      pointsOfInterest: ['Parque Central', 'Museo de Antropología', 'Catedral de San Pedro'],
    },
    Pekín: {
      name: 'Pekín',
      image: '../src/assets/ciudades/pekin.jpg',
      details: 'Pekín es la capital de China, conocida por su historia imperial y su vibrante vida moderna.',
      pointsOfInterest: ['Ciudad Prohibida', 'Gran Muralla China', 'Templo del Cielo'],
    },
    Shanghái: {
      name: 'Shanghái',
      image: '../src/assets/ciudades/shanghai.jpg',
      details: 'Shanghái es una metrópolis global en China, famosa por su impresionante skyline y su vida nocturna.',
      pointsOfInterest: ['The Bund', 'Torre Jin Mao', 'Jardín Yuyuan'],
    },
    "Xi'an": {
      name: 'Xi\'an',
      image: '../src/assets/ciudades/xian.jpg',
      details: 'Xi\'an es conocida por su historia antigua y su famosa Terracota Army.',
      pointsOfInterest: ['Guerreros de Terracota', 'Murallas de Xi\'an', 'Gran Mezquita'],
    },
    Tokio: {
      name: 'Tokio',
      image: '../src/assets/ciudades/tokio.jpg',
      details: 'Tokio es la capital de Japón, conocida por su mezcla única de tradición y modernidad.',
      pointsOfInterest: ['Templo Senso-ji', 'Shibuya Crossing', 'Palacio Imperial'],
    },
    Kioto: {
      name: 'Kioto',
      image: '../src/assets/ciudades/kioto.jpg',
      details: 'Kioto es famosa por sus templos antiguos, sus jardines zen y su rica herencia cultural.',
      pointsOfInterest: ['Templo Kinkaku-ji', 'Santuario Fushimi Inari', 'Arashiyama Bamboo Grove'],
    },
    Osaka: {
      name: 'Osaka',
      image: '../src/assets/ciudades/osaka.jpg',
      details: 'Osaka es conocida por su comida callejera, su vibrante vida nocturna y su castillo histórico.',
      pointsOfInterest: ['Castillo de Osaka', 'Dotonbori', 'Universal Studios Japan'],
    },
    Delhi: {
      name: 'Delhi',
      image: '../src/assets/ciudades/delhi.jpg',
      details: 'Delhi es la capital de India, famosa por su rica historia y su vida urbana vibrante.',
      pointsOfInterest: ['Qutub Minar', 'Templo del Loto', 'India Gate'],
    },
    Mumbai: {
      name: 'Mumbai',
      image: '../src/assets/ciudades/mumbai.jpg',
      details: 'Mumbai es el centro financiero de India y conocida por su industria del cine Bollywood.',
      pointsOfInterest: ['Puerta de la India', 'Marine Drive', 'Elephanta Caves'],
    },
    Agra: {
      name: 'Agra',
      image: '../src/assets/ciudades/agra.jpg',
      details: 'Agra es famosa por el Taj Mahal, una de las maravillas del mundo.',
      pointsOfInterest: ['Taj Mahal', 'Fuerte de Agra', 'Mehtab Bagh'],
    },
    Bangkok: {
      name: 'Bangkok',
      image: '../src/assets/ciudades/bangkok.jpg',
      details: 'Bangkok es la capital de Tailandia, conocida por sus templos impresionantes y su vida nocturna vibrante.',
      pointsOfInterest: ['Gran Palacio', 'Wat Arun', 'Mercado Flotante Damnoen Saduak'],
    },
    'Chiang Mai': {
      name: 'Chiang Mai',
      image: '../src/assets/ciudades/chiang-mai.jpg',
      details: 'Chiang Mai es famosa por sus templos antiguos, sus mercados nocturnos y sus festivales.',
      pointsOfInterest: ['Templo Doi Suthep', 'Mercado Nocturno', 'Ciudad Vieja de Chiang Mai'],
    },
    Phuket: {
      name: 'Phuket',
      image: '../src/assets/ciudades/phuket.jpg',
      details: 'Phuket es conocida por sus playas tropicales y su vibrante vida nocturna.',
      pointsOfInterest: ['Patong Beach', 'Templo Wat Chalong', 'Isla Phi Phi'],
    },
    París: {
      name: 'París',
      image: '../src/assets/ciudades/paris.jpg',
      details: 'París es la capital de Francia, famosa por su arquitectura icónica y su rica cultura.',
      pointsOfInterest: ['Torre Eiffel', 'Museo del Louvre', 'Catedral de Notre-Dame'],
    },
    Niza: {
      name: 'Niza',
      image: '../src/assets/ciudades/niza.jpg',
      details: 'Niza es conocida por sus playas y su clima mediterráneo.',
      pointsOfInterest: ['Promenade des Anglais', 'Vieille Ville', 'Museo Matisse'],
    },
    Lyon: {
      name: 'Lyon',
      image: '../src/assets/ciudades/lyon.jpg',
      details: 'Lyon es famosa por su gastronomía y su arquitectura renacentista.',
      pointsOfInterest: ['Vieux Lyon', 'Basilica of Notre-Dame de Fourvière', 'Parc de la Tête d\'Or'],
    },
    Roma: {
      name: 'Roma',
      image: '../src/assets/ciudades/roma.jpg',
      details: 'Roma es la capital de Italia, conocida por sus ruinas antiguas y su historia rica.',
      pointsOfInterest: ['Coliseo', 'Fontana di Trevi', 'Vaticano'],
    },
    Venecia: {
      name: 'Venecia',
      image: '../src/assets/ciudades/venecia.jpg',
      details: 'Venecia es famosa por sus canales y su arquitectura única.',
      pointsOfInterest: ['Gran Canal', 'Plaza de San Marcos', 'Puente de Rialto'],
    },
    Florencia: {
      name: 'Florencia',
      image: '../src/assets/ciudades/florencia.jpg',
      details: 'Florencia es conocida por su arte renacentista y su arquitectura histórica.',
      pointsOfInterest: ['Catedral de Santa María del Fiore', 'Galería Uffizi', 'Puente Vecchio'],
    },
    Barcelona: {
      name: 'Barcelona',
      image: '../src/assets/ciudades/barcelona.jpg',
      details: 'Barcelona es conocida por su arquitectura modernista y su vibrante vida cultural.',
      pointsOfInterest: ['Sagrada Familia', 'Parc Güell', 'La Rambla'],
    },
    Madrid: {
      name: 'Madrid',
      image: '../src/assets/ciudades/madrid.jpg',
      details: 'Madrid es la capital de España, famosa por sus museos y su vida nocturna.',
      pointsOfInterest: ['Museo del Prado', 'Parque del Retiro', 'Plaza Mayor'],
    },
    Sevilla: {
      name: 'Sevilla',
      image: '../src/assets/ciudades/sevilla.jpg',
      details: 'Sevilla es conocida por su arquitectura histórica y sus festivales coloridos.',
      pointsOfInterest: ['Alcázar de Sevilla', 'Catedral de Sevilla', 'Plaza de España'],
    },
    Londres: {
        name: 'Londres',
        image: '../src/assets/ciudades/londres.jpg',
        details: 'Londres es la capital del Reino Unido, conocida por su historia rica y sus monumentos icónicos.',
        pointsOfInterest: ['Torre de Londres', 'Museo Británico', 'Palacio de Buckingham'],
      },
      Edimburgo: {
        name: 'Edimburgo',
        image: '../src/assets/ciudades/edimburgo.jpg',
        details: 'Edimburgo es la capital de Escocia, famosa por su festival anual y su impresionante castillo.',
        pointsOfInterest: ['Castillo de Edimburgo', 'Royal Mile', 'Palacio de Holyroodhouse'],
      },
      Manchester: {
        name: 'Manchester',
        image: '../src/assets/ciudades/manchester.jpg',
        details: 'Manchester es conocida por su influencia en la industria musical y su rica historia industrial.',
        pointsOfInterest: ['Museo de Manchester', 'Biblioteca John Rylands', 'Old Trafford'],
      },
      Sídney: {
        name: 'Sídney',
        image: '../src/assets/ciudades/sidney.jpg',
        details: 'Sídney es famosa por su icónica Ópera y su vibrante vida cultural.',
        pointsOfInterest: ['Ópera de Sídney', 'Puente del Puerto de Sídney', 'Bondi Beach'],
      },
      Melbourne: {
        name: 'Melbourne',
        image: '../src/assets/ciudades/melbourne.jpg',
        details: 'Melbourne es conocida por su vibrante escena cultural y su gran oferta gastronómica.',
        pointsOfInterest: ['Federation Square', 'Jardín Botánico Real', 'Museo de Melbourne'],
      },
      Brisbane: {
        name: 'Brisbane',
        image: '../src/assets/ciudades/brisbane.jpg',
        details: 'Brisbane es una ciudad moderna con una vibrante vida nocturna y un clima subtropical.',
        pointsOfInterest: ['South Bank', 'Lone Pine Koala Sanctuary', 'Galería de Arte Moderno'],
      },
      Auckland: {
        name: 'Auckland',
        image: '../src/assets/ciudades/auckland.jpg',
        details: 'Auckland es la ciudad más grande de Nueva Zelanda, conocida por su puerto y su vibrante vida cultural.',
        pointsOfInterest: ['Sky Tower', 'Museo de Auckland', 'Isla Waiheke'],
      },
      Wellington: {
        name: 'Wellington',
        image: '../src/assets/ciudades/wellington.jpg',
        details: 'Wellington es la capital de Nueva Zelanda, famosa por su escena artística y su puerto.',
        pointsOfInterest: ['Te Papa Museum', 'Cable Car', 'Mount Victoria'],
      },
      Queenstown: {
        name: 'Queenstown',
        image: '../src/assets/ciudades/queenstown.jpg',
        details: 'Queenstown es conocida por sus impresionantes paisajes y sus oportunidades para actividades al aire libre.',
        pointsOfInterest: ['Lago Wakatipu', 'Skyline Gondola', 'Milford Sound'],
      },
      Suva: {
        name: 'Suva',
        image: '../src/assets/ciudades/suva.jpg',
        details: 'Suva es la capital de Fiyi, conocida por su arquitectura colonial y su vibrante vida cultural.',
        pointsOfInterest: ['Museo de Fiyi', 'Jardín Botánico de Suva', 'Mercado de Suva'],
      },
      Nadi: {
        name: 'Nadi',
        image: '../src/assets/ciudades/nadi.jpg',
        details: 'Nadi es famosa por sus playas cercanas y su vibrante ambiente turístico.',
        pointsOfInterest: ['Templo Sri Siva Subramaniya', 'Jardín del Cielo', 'Playa de Denarau'],
      },
      Savusavu: {
        name: 'Savusavu',
        image: '../src/assets/ciudades/savusavu.jpg',
        details: 'Savusavu es conocida por su entorno natural prístino y sus aguas termales.',
        pointsOfInterest: ['Hot Springs', 'Bahía de Savusavu', 'Parque Nacional de Bouma'],
      },
      'Port Moresby': {
        name: 'Port Moresby',
        image: '../src/assets/ciudades/port-moresby.jpg',
        details: 'Port Moresby es la capital de Papúa Nueva Guinea, conocida por su desarrollo urbano y su entorno costero.',
        pointsOfInterest: ['Museo Nacional y Galería de Arte', 'Jardín Botánico', 'Parque de la Ciudad'],
      },
      Lae: {
        name: 'Lae',
        image: '../src/assets/ciudades/lae.jpg',
        details: 'Lae es un importante puerto y centro comercial en Papúa Nueva Guinea, conocido por su industria y su entorno natural.',
        pointsOfInterest: ['Parque de Vida Silvestre de Lae', 'Mercado de Lae', 'Universidad de Lae'],
      },
      'Mount Hagen': {
        name: 'Mount Hagen',
        image: '../src/assets/ciudades/mount-hagen.jpg',
        details: 'Mount Hagen es conocida por su entorno montañoso y su mercado local.',
        pointsOfInterest: ['Mercado de Mount Hagen', 'Parque Nacional de Hagen', 'Montañas de Hagen'],
      }
    };
  
  
  export default citiesData;
  